[package]
name = "rings"
version = "0.1.0"
edition = "2024"

[dependencies]
index_vec = "0.1.4"
interavl = "0.5.0"

[features]
debug_lexer=[]
debug_tasks=[]
debug_parser=[]
debug_type_checker=[]
debug_packer=[]
debug_layout=[]
debug_tac=[]
debug_asm=[]

record=[]
procedures=[]
table=[]
index=[]
forloop=[]
call=[]
optimize=[]
types=[]
notes=[]
